apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-deployment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chahatsagarmain/argo-cd-kubernetes-pipeline.git
    targetRevision: HEAD
    path: canary
  destination:
    server: https://kubernetes.default.svc
    namespace: canary
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
    - CreateNamespace=true